name: dev
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - freetype=2.9.1=hb4e5f40_0
  - imageio=2.5.0=py37_0
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.0.10=hcb84e12_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.16.5=py37hacdab7b_0
  - numpy-base=1.16.5=py37h6575580_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h1de35cc_1
  - pillow=6.1.0=py37hb68e598_0
  - python=3.7.4=h359304d_1
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - attrs==19.1.0
    - chardet==3.0.4
    - cloudpickle==1.2.2
    - decorator==4.4.0
    - dill==0.3.0
    - future==0.17.1
    - gast==0.3.2
    - google-pasta==0.1.7
    - googleapis-common-protos==1.6.0
    - grpcio==1.23.0
    - h5py==2.10.0
    - idna==2.8
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - pip==19.2.3
    - promise==2.2.1
    - protobuf==3.9.1
    - psutil==5.6.3
    - requests==2.22.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-datasets==1.2.0
    - tensorflow-estimator==1.14.0
    - tensorflow-metadata==0.14.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - tqdm==4.36.0
    - urllib3==1.25.3
    - werkzeug==0.15.6
    - wrapt==1.11.2
prefix: /usr/local/anaconda3/envs/dev

